language: c
sudo: false
script:
  - mkdir build
  - cd build 
  - cmake ..
  - make
  - make test
addons:
  apt:
    packages:
    - libusb-1.0-dev
    - libelf-dev
    - liblua5.2-dev
    - lua5.2
    - pkg-config
    - valgrind
    - cmake