language: c
sudo: required
before_install:
  - sudo apt-add-repository -y ppa:kalakris/cmake
  - sudo apt-get update 
  - sudo apt-get install -y cmake
script:
  - cmake --version
  - mkdir build
  - cd build 
  - cmake ..
  - make
  - make test
addons:
  apt:
    packages:
    - libelf-dev
    - liblua5.2-dev
    - lua5.2
    - pkg-config
    - valgrind